In [1]:
import numpy as np
import torch
import matplotlib.pyplot as plt
import torch.nn as nn
from torch.nn import functional as F
from torch.autograd import Variable

In [2]:
a=torch.full((13,13),1)
a

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [3]:
a[:,1:2]=2
a[:,6:7]=2
a[:,11:12]=2
a[1:2,:]=2
a[6:7,:]=2
a[11:12,:]=2
a[3:5,3:5]=3
a[8:10,8:10]=3
a[3:5,8:10]=3
a[8:10,3:5]=3
a

tensor([[1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 3., 3., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.]])

In [4]:
#torch.normal(5000,5000)
a=torch.empty(5000,5000).normal_()
b=torch.empty(5000,5000).normal_()

In [5]:
from time import perf_counter
start=perf_counter()
c=torch.mm(a,b)
stop=perf_counter()
print("Multiplication : ",c)
print("multiplication is done is second",stop-start)

Multiplication :  tensor([[ -59.4537,   44.6517,  -16.3595,  ...,  107.2986,   -2.1593,
          -75.2942],
        [  30.7156,   69.7090,  -38.8507,  ...,   39.0212,  -29.9257,
          -17.9158],
        [ -34.0691,   -5.7095,  -44.5120,  ...,   95.4178,   70.5477,
          -45.8479],
        ...,
        [-100.3642,   99.7244,  -21.6913,  ...,   51.8831,  -23.7370,
           61.3072],
        [  39.3019,    4.9676,   85.0117,  ...,  -84.2062,   25.8518,
           89.9796],
        [  79.2457,  -15.7449,  163.2459,  ...,  105.1225,  -20.7009,
           17.1360]])
multiplication is done is second 0.721438787993975


In [6]:
def mul_row(arr2D):
    l=len(arr2D)
    newarr=arr2D
    for k in range(0,l):
        #print(l)
        #print(k)
        newarr[k]=arr2D[k] * (k+1)
        #print(newarr)
        
    return newarr

In [7]:
mat=torch.full((3,3),2)
mat

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [8]:
mul_row(mat)

tensor([[2., 2., 2.],
        [4., 4., 4.],
        [6., 6., 6.]])

## Multi Layer perceptron with one hidden layer from scratch

Activation Function

In [9]:
def sigma(x):
    return x.tanh()

def dsigma(x):
    return 4 * (x.exp() + x.mul(-1).exp()).pow(-2)

Loss function

In [10]:
def loss(v,t):
    return torch.sum(torch.pow((t-v),2))

def dloss(v,t):
    return torch.mul(v-t, 2)

load dataset

In [11]:
from dlc_practical_prologue import load_data
train_input, train_target, test_input, test_target = load_data(one_hot_labels=True,normalize=True)
print("training size:",train_input.shape)
print("test size:",test_input.shape)
print("training target size:",train_target.shape)
print("test target size:",test_target.shape)

* Using MNIST
** Reduce the data-set (use --full for the full thing)
** Use 1000 train and 1000 test samples
training size: torch.Size([1000, 784])
test size: torch.Size([1000, 784])
training target size: torch.Size([1000, 10])
test target size: torch.Size([1000, 10])


/home/aims/.local/lib/python3.7/site-packages/torchvision/datasets/mnist.py:53: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/home/aims/.local/lib/python3.7/site-packages/torchvision/datasets/mnist.py:43: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/home/aims/.local/lib/python3.7/site-packages/torchvision/datasets/mnist.py:58: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/home/aims/.local/lib/python3.7/site-packages/torchvision/datasets/mnist.py:48: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [12]:
eps=1e-6
w1=torch.empty(50,train_input.shape[1]).normal_(0,eps)
b1=torch.empty(50,1)
w2=torch.empty(train_target.shape[1],50).normal_(0,eps)
b2=torch.empty(train_target.shape[1],1)
dl_dw1=torch.empty(w1.size())
dl_db1=torch.empty(b1.size())
dl_db2=torch.empty(b2.size())
dl_dw2=torch.empty(w2.size())


In [13]:
def forward_pass(w1,b1,w2,b2,x):
    s1=torch.mv(w1,x) + b1
    x1=sigma(s1)
    s2=torch.mv(w2,x1)+b2
    x2=sigma(s2)
    return x,s1,x1,s2,x2

In [17]:
def backward_pass(w1, b1, w2, b2,
                  t,
                  x, s1, x1, s2, x2,
                  dl_dw1, dl_db1, dl_dw2, dl_db2):
    x0 = x
    dl_dx2 = dloss(x2, t)
    #print(dsigma(s2))
    dl_ds2 = dl_dx2*dsigma(s2)
    dl_dx1 = w2.t().mv(dl_ds2)
    dl_ds1 = dsigma(s1) * dl_dx1

    dl_dw2.add_(dl_ds2.view(-1, 1).mm(x1.view(1, -1)))
    dl_db2.add_(dl_ds2)
    dl_dw1.add_(dl_ds1.view(-1, 1).mm(x0.view(1, -1)))
    dl_db1.add_(dl_ds1)

In [18]:

#train_input, train_target, test_input, test_target = prologue.load_data(one_hot_labels = True,
                                                     #                   normalize = True)
nb_classes = train_target.size(1)
nb_train_samples = train_input.size(0)

zeta = 0.90

train_input = train_input * zeta
test_input = test_input * zeta

nb_hidden = 50
eta = 1e-1 / nb_train_samples
epsilon = 1e-6

w1 = torch.empty(nb_hidden, train_input.size(1)).normal_(0, epsilon)
b1 = torch.empty(nb_hidden).normal_(0, epsilon)
w2 = torch.empty(nb_classes, nb_hidden).normal_(0, epsilon)
b2 = torch.empty(nb_classes).normal_(0, epsilon)

dl_dw1 = torch.empty(w1.size())
dl_db1 = torch.empty(b1.size())
dl_dw2 = torch.empty(w2.size())
dl_db2 = torch.empty(b2.size())

for k in range(1000):

    # Back-prop

    acc_loss = 0
    nb_train_errors = 0

    dl_dw1.zero_()
    dl_db1.zero_()
    dl_dw2.zero_()
    dl_db2.zero_()

    for n in range(nb_train_samples):
        x0, s1, x1, s2, x2 = forward_pass(w1, b1, w2, b2, train_input[n])

        pred = x2.max(0)[1].item()
        if train_target[n, pred] < 0.5: 
            nb_train_errors = nb_train_errors + 1
            acc_loss = acc_loss + loss(x2, train_target[n])

        backward_pass(w1, b1, w2, b2,
                      train_target[n],
                      x0, s1, x1, s2, x2,
                      dl_dw1, dl_db1, dl_dw2, dl_db2)

    # Gradient step

    w1 = w1 - eta * dl_dw1
    b1 = b1 - eta * dl_db1
    w2 = w2 - eta * dl_dw2
    b2 = b2 - eta * dl_db2

    # Test error

    nb_test_errors = 0

    for n in range(test_input.size(0)):
        _, _, _, _, x2 = forward_pass(w1, b1, w2, b2, test_input[n])

        pred = x2.max(0)[1].item()
        if test_target[n, pred] < 0.5: nb_test_errors = nb_test_errors + 1

    print('{:d} acc_train_loss {:.02f} acc_train_error {:.02f}% test_error {:.02f}%'
          .format(k,
                  acc_loss,
                  (100 * nb_train_errors) / train_input.size(0),
                  (100 * nb_test_errors) / test_input.size(0)))

0 acc_train_loss 900.00 acc_train_error 90.00% test_error 90.10%
1 acc_train_loss 851.68 acc_train_error 88.30% test_error 90.10%
2 acc_train_loss 831.78 acc_train_error 88.30% test_error 90.10%
3 acc_train_loss 819.15 acc_train_error 88.30% test_error 90.10%
4 acc_train_loss 811.14 acc_train_error 88.30% test_error 90.10%
5 acc_train_loss 806.07 acc_train_error 88.30% test_error 90.10%
6 acc_train_loss 802.87 acc_train_error 88.30% test_error 90.10%
7 acc_train_loss 800.86 acc_train_error 88.30% test_error 90.10%
8 acc_train_loss 799.59 acc_train_error 88.30% test_error 90.10%
9 acc_train_loss 798.80 acc_train_error 88.30% test_error 90.10%
10 acc_train_loss 798.31 acc_train_error 88.30% test_error 90.10%
11 acc_train_loss 798.02 acc_train_error 88.30% test_error 90.10%
12 acc_train_loss 797.84 acc_train_error 88.30% test_error 90.10%
13 acc_train_loss 797.73 acc_train_error 88.30% test_error 90.10%
14 acc_train_loss 797.67 acc_train_error 88.30% test_error 90.10%
15 acc_train_loss 79

124 acc_train_loss 130.17 acc_train_error 15.40% test_error 25.10%
125 acc_train_loss 130.07 acc_train_error 15.40% test_error 24.60%
126 acc_train_loss 128.08 acc_train_error 15.20% test_error 23.90%
127 acc_train_loss 126.51 acc_train_error 14.90% test_error 23.80%
128 acc_train_loss 121.04 acc_train_error 14.30% test_error 24.30%
129 acc_train_loss 130.98 acc_train_error 15.30% test_error 22.80%
130 acc_train_loss 116.69 acc_train_error 13.40% test_error 32.60%
131 acc_train_loss 188.81 acc_train_error 20.10% test_error 27.80%
132 acc_train_loss 157.66 acc_train_error 15.40% test_error 33.80%
133 acc_train_loss 206.32 acc_train_error 21.60% test_error 24.20%
134 acc_train_loss 131.56 acc_train_error 15.10% test_error 24.00%
135 acc_train_loss 117.24 acc_train_error 13.00% test_error 32.70%
136 acc_train_loss 186.79 acc_train_error 20.10% test_error 28.30%
137 acc_train_loss 150.04 acc_train_error 16.40% test_error 27.10%
138 acc_train_loss 139.42 acc_train_error 15.40% test_error 23

249 acc_train_loss 52.84 acc_train_error 6.00% test_error 17.30%
250 acc_train_loss 65.13 acc_train_error 7.40% test_error 16.80%
251 acc_train_loss 48.70 acc_train_error 5.40% test_error 17.40%
252 acc_train_loss 63.67 acc_train_error 7.20% test_error 16.60%
253 acc_train_loss 47.57 acc_train_error 5.20% test_error 17.70%
254 acc_train_loss 64.94 acc_train_error 7.40% test_error 16.70%
255 acc_train_loss 47.72 acc_train_error 5.20% test_error 17.80%
256 acc_train_loss 65.31 acc_train_error 7.40% test_error 16.70%
257 acc_train_loss 46.30 acc_train_error 4.90% test_error 17.50%
258 acc_train_loss 64.80 acc_train_error 7.30% test_error 16.50%
259 acc_train_loss 48.09 acc_train_error 5.10% test_error 17.20%
260 acc_train_loss 60.23 acc_train_error 6.70% test_error 16.50%
261 acc_train_loss 49.93 acc_train_error 5.40% test_error 17.50%
262 acc_train_loss 54.70 acc_train_error 6.00% test_error 16.30%
263 acc_train_loss 51.14 acc_train_error 5.60% test_error 17.40%
264 acc_train_loss 53.25 

376 acc_train_loss 40.81 acc_train_error 4.40% test_error 17.70%
377 acc_train_loss 36.56 acc_train_error 4.00% test_error 15.60%
378 acc_train_loss 41.25 acc_train_error 4.60% test_error 17.10%
379 acc_train_loss 35.80 acc_train_error 4.00% test_error 15.20%
380 acc_train_loss 37.30 acc_train_error 4.20% test_error 16.70%
381 acc_train_loss 34.40 acc_train_error 3.90% test_error 15.10%
382 acc_train_loss 36.59 acc_train_error 4.20% test_error 16.20%
383 acc_train_loss 34.14 acc_train_error 3.90% test_error 14.70%
384 acc_train_loss 36.85 acc_train_error 4.30% test_error 16.70%
385 acc_train_loss 34.11 acc_train_error 3.90% test_error 14.50%
386 acc_train_loss 36.49 acc_train_error 4.20% test_error 17.40%
387 acc_train_loss 34.60 acc_train_error 3.90% test_error 14.40%
388 acc_train_loss 38.61 acc_train_error 4.40% test_error 17.50%
389 acc_train_loss 35.18 acc_train_error 3.90% test_error 14.80%
390 acc_train_loss 38.51 acc_train_error 4.40% test_error 16.80%
391 acc_train_loss 32.76 

503 acc_train_loss 25.10 acc_train_error 3.10% test_error 15.80%
504 acc_train_loss 22.67 acc_train_error 2.70% test_error 15.60%
505 acc_train_loss 22.05 acc_train_error 2.70% test_error 15.30%
506 acc_train_loss 22.58 acc_train_error 2.70% test_error 15.50%
507 acc_train_loss 21.04 acc_train_error 2.60% test_error 15.30%
508 acc_train_loss 22.98 acc_train_error 2.80% test_error 15.10%
509 acc_train_loss 20.65 acc_train_error 2.60% test_error 15.10%
510 acc_train_loss 22.83 acc_train_error 2.80% test_error 15.00%
511 acc_train_loss 18.51 acc_train_error 2.30% test_error 15.10%
512 acc_train_loss 22.15 acc_train_error 2.70% test_error 14.50%
513 acc_train_loss 18.43 acc_train_error 2.30% test_error 14.90%
514 acc_train_loss 20.92 acc_train_error 2.50% test_error 14.30%
515 acc_train_loss 18.94 acc_train_error 2.40% test_error 14.90%
516 acc_train_loss 20.96 acc_train_error 2.50% test_error 14.50%
517 acc_train_loss 17.11 acc_train_error 2.10% test_error 15.40%
518 acc_train_loss 22.23 

630 acc_train_loss 11.03 acc_train_error 1.40% test_error 15.80%
631 acc_train_loss 13.37 acc_train_error 1.70% test_error 15.60%
632 acc_train_loss 12.75 acc_train_error 1.60% test_error 16.00%
633 acc_train_loss 13.71 acc_train_error 1.70% test_error 15.50%
634 acc_train_loss 14.27 acc_train_error 1.80% test_error 16.30%
635 acc_train_loss 13.16 acc_train_error 1.60% test_error 15.40%
636 acc_train_loss 13.66 acc_train_error 1.70% test_error 15.80%
637 acc_train_loss 13.16 acc_train_error 1.60% test_error 14.80%
638 acc_train_loss 11.36 acc_train_error 1.40% test_error 15.80%
639 acc_train_loss 12.94 acc_train_error 1.60% test_error 14.50%
640 acc_train_loss 11.30 acc_train_error 1.40% test_error 15.70%
641 acc_train_loss 12.76 acc_train_error 1.60% test_error 14.40%
642 acc_train_loss 13.42 acc_train_error 1.70% test_error 15.80%
643 acc_train_loss 11.32 acc_train_error 1.40% test_error 14.60%
644 acc_train_loss 15.60 acc_train_error 2.00% test_error 16.30%
645 acc_train_loss 11.77 

757 acc_train_loss 7.10 acc_train_error 1.00% test_error 15.00%
758 acc_train_loss 7.56 acc_train_error 1.00% test_error 15.70%
759 acc_train_loss 6.45 acc_train_error 0.90% test_error 15.00%
760 acc_train_loss 8.12 acc_train_error 1.10% test_error 15.50%
761 acc_train_loss 6.44 acc_train_error 0.90% test_error 15.10%
762 acc_train_loss 8.72 acc_train_error 1.20% test_error 15.10%
763 acc_train_loss 7.06 acc_train_error 1.00% test_error 14.90%
764 acc_train_loss 8.10 acc_train_error 1.10% test_error 14.70%
765 acc_train_loss 7.08 acc_train_error 1.00% test_error 15.10%
766 acc_train_loss 8.05 acc_train_error 1.10% test_error 14.80%
767 acc_train_loss 5.85 acc_train_error 0.80% test_error 15.50%
768 acc_train_loss 8.02 acc_train_error 1.10% test_error 14.70%
769 acc_train_loss 7.22 acc_train_error 1.00% test_error 15.00%
770 acc_train_loss 7.33 acc_train_error 1.00% test_error 14.60%
771 acc_train_loss 7.29 acc_train_error 1.00% test_error 14.90%
772 acc_train_loss 6.70 acc_train_error 

886 acc_train_loss 2.40 acc_train_error 0.30% test_error 15.70%
887 acc_train_loss 5.12 acc_train_error 0.70% test_error 15.00%
888 acc_train_loss 2.36 acc_train_error 0.30% test_error 15.40%
889 acc_train_loss 5.07 acc_train_error 0.70% test_error 14.80%
890 acc_train_loss 2.33 acc_train_error 0.30% test_error 15.60%
891 acc_train_loss 5.02 acc_train_error 0.70% test_error 14.80%
892 acc_train_loss 2.30 acc_train_error 0.30% test_error 15.80%
893 acc_train_loss 4.97 acc_train_error 0.70% test_error 14.60%
894 acc_train_loss 2.28 acc_train_error 0.30% test_error 15.60%
895 acc_train_loss 4.83 acc_train_error 0.70% test_error 14.30%
896 acc_train_loss 2.88 acc_train_error 0.40% test_error 15.60%
897 acc_train_loss 4.20 acc_train_error 0.60% test_error 14.50%
898 acc_train_loss 2.87 acc_train_error 0.40% test_error 15.50%
899 acc_train_loss 3.60 acc_train_error 0.50% test_error 14.50%
900 acc_train_loss 2.87 acc_train_error 0.40% test_error 15.60%
901 acc_train_loss 3.58 acc_train_error 